### ISSUE TITLE
Take directory as input and deduce list of deps according to visible files

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/dash-licenses#124]
In order to unify how to work with this tool and to write extremely reusable scripts or other forms of CI/GitHub actions to automate checks, it would be nice that the tool can take a project directory as input and builds the list of dependencies to check according to the local files in the directory. For example, if Maven is used, it would take care of invoking `mvn dependency:list ...`, if package.json is used, it would use it and so on.
With this, running the tool on a project would most often be `java license.jar .`.

**Comment by waynebeaton** [comment]
For one... stop using `mvn dependency:list` and just use the Maven plugin. `dependency:list` seems to only work consistently after running `verify`, but the Dash License Tool's Maven plugin just works right out of the blocks, supports exclusions, etc.. It also doesn't depend on getting a regular expression _just right_.

Finding `package-lock.json` and `yarn.lock` files seems easy enough, and desirable. My experience with Maven builds is that just blindly running Maven against a `pom.xml` file works most (or at least a lot) of the time, but I very often have to scan READMEs for build information or look at CI, and tinker with parameters to execute in a particular order. This gives me pause that we would be able to automatically do much in a consistent manner. Having said all that, not doing anything because we can't do everything isn't smart.

I had originally intended the tool to just do the work of analyzing the dependencies that it is given and am hesitant to expand the scope. We can probably do a lot with just piping `find` results into the CLI.

Finally, we're already duplicating a lot of the work that is already done by a tool that we're [investigating](https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/98) as a possible replacement for everything. We're starting work in earnest to see whether or not we can deploy OSS Review Toolkit (ORT) for all Eclipse projects. If we can pull this off, the entire IP process will be mostly completely automated and hands-off for committers. My understanding at this point is that we can point ORT at our list of repositories and it will just chug through everything looking at licensing, security vulnerabilities, and more. It will require some configuration, but I'm hopeful that it will engage the IP Team directly and we'll only have to bother committers when we actually find something that either can't be resolved or we need help resolving. ORT does automatically identify and analyse build scripts, and it supports a lot more that we do.

If we can make ORT work, then we don't need the Dash License Tool. FWIW, at least some parts of the Dash License Tool will live on as customization/rules for ORT.

So... I'm not saying no, I'm just saying that I'm hesitant to try and take this too far when we have a better and more complete solution on the horizon.

**Comment by waynebeaton** [comment]
While I think that this is interesting, I'm going to mark this issue as backlog and close it.

The requested feature is out of scope. We might consider doing something like this later, but IMHO, the Dash License Tool is part of that solution, not the solution.
