### ISSUE TITLE
Wrong analysis with some modules

### ISSUE THREAD

**Issue by phkrief** [eclipse/dash-licenses#127]
The DASH Tool analysis of the following repo: https://github.com/eclipse-researchlabs/smartclide-context mentions:

> License information could not be automatically verified for the following content:
> ../...
> - maven/mavencentral/de.atb.context/context-core/2.0.0
> - maven/mavencentral/de.atb.context/context-monitoring/2.0.0
> .../...
> when actually, they are part of the current repository and their license is well defined.

Actually, these 2 dependencies are part of the repository. They are modules and their license is well defined.

Does this misinterpretation come from the pom.xml which is not correctly set or does it come from something else?
Thx a lot

**Comment by waynebeaton** [comment]
The tool doesn't know anything about the repository. It only understands the content ids that are presented to it. It doesn't know how to inspect a Maven `pom.xml` file, for example, and understand where content comes from. The Maven plugin uses the Maven reactor to get the dependency tree, which it then feeds to the tool which ultimately checks the content with the backend.

The backend basically knows about Eclipse project content and third party content. Since the repository that you're running against isn't Eclipse code, it's assumed to be third party code and treated as such.

If the content were Eclipse project code, we'd add a rule to the backend to identify it.

The workaround is to configure the tool to ignore that content.

````
$ mvn org.eclipse.dash:license-tool-plugin:license-check -DexcludeGroupIds=de.atb
````

This feature isn't documented yet. I have an issue open for that (see #110).

**Comment by phkrief** [comment]
Oops! Very good point @waynebeaton. I mixed up both tools using them together.
Thanks for the parameter ignoring some groupIds. Good to know!
