### ISSUE TITLE
Automatic IP Team Review Requests: ready for CI integration?

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse/dash-licenses#129]
Hi,

For our project (theia) I have noticed that `dash-licenses'`  results have stabilised, with only the occasional few new dependencies to handle. I was wondering if the tool would be ready to be run in `automatic IP team review` mode, as part of CI? We already run it as part of our CI, and then manually run it in automated mode, when required. 

WDYT?

P.S. from a user's PoV, this runs like magic. I am curious how much manual work is still required in the backend? Are easy cases completely automated? (it looks that way, given the really quick turn-around time we typically experience, when nothing strange is found in the scan or on `clearlydefined`)

**Comment by waynebeaton** [comment]
It's a worthy experiment. Let's go for it. Please make sure that the token is protected.

If it ends up dumping 1000 review requests on us, you might hear faint screaming from our direction.

For the most part the vetting process is entirely automatic. In cases were licenses that are not on our approved list are detected or there are other anomalies, human intervention is required. To a large degree, I've been doing the human intervention part so that I can better understand the issues and tune the scripts to improve the quality of the automation. We're at a point now, where we're going to turn the human intervention part over to the IP Team and run the "IP Lab" repository more like IPZilla.

**Comment by marcdumais-work** [comment]
Sounds like a plan! 

> If it ends up dumping 1000 review requests on us, you might hear faint screaming from our direction.

Understood. We are of course willing to disable this, if it ends-up causing you problems - just let us know.

> Please make sure that the token is protected

Will do.

Big thanks, Wayne, for your great work here, automating the tedious parts of 3PP license checks - such a big improvement, compared to a couple of years ago!

**Comment by marcdumais-work** [comment]
Heads-up: we have a PR that introduces using the `Automatic IP Team Review Requests` mode of `dash-licenses` for the main Theia repo: https://github.com/eclipse-theia/theia/pull/11766

We can easily switch-back if it causes too much problems for the IP team.
