### ISSUE TITLE
Maven regex pattern removes version qualifier 

### ISSUE THREAD

**Issue by sophokles73** [eclipse/dash-licenses#17]
The regex pattern used by the `MavenIdParser` strips any qualifier from the version string. This might be appropriate for handling p2 bundles (which I have no clue about) but it is certainly not correct for plain Maven dependencies.

For example the dependency `com.google.guava:guava:jar:28.0-jre:compile` results in a ID with version `28.0` when it should be `28.0-jre`. The same problem would arise for versions containing a qualifier as often used in OSGi bundles like `1.3.0.Final` or `1.2.1.RELEASE`. This behavior results in failure to determine license information for such dependencies.

FMPOV the resulting `ContentId` instance's version should be the verbatim copy of the version string from the maven coordinates.
If we need extra handling for p2 bundles then we probably should add a `P2IdParser` which detects a p2 bundle by means of the group ID starting with `p2.eclipse-`.

**Comment by waynebeaton** [comment]
This was originally intentional. our IP Policy regards service releases as license-equivalent to each other and their parent minor release, so I was trying to collapse them. But I agree with your reasoning and have pushed an update that retains the qualifiers. 

The IPZilla service that this calls will take care of managing the equivalences between versions. Retaining the qualifier information gives us more flexibility to handle exceptions in the service.

We do need a better way to handle p2 bundles. I'll open a separate issue for this.
