### ISSUE TITLE
license-check claims org.objectweb.asm.tree/8.0.1.v20200420-1007 needs to be vetted

### ISSUE THREAD

**Issue by msohn** [eclipse/dash-licenses#189]
I am trying to configure the EGit build to fail the build if we add a dependency to any library which doesn't pass the dash license check, see https://git.eclipse.org/r/c/egit/egit/+/196335.

With this change the build fails with [this error](https://ci.eclipse.org/egit/job/egit.gerrit/2730/console):

```
00:07:08  22:07:08 [INFO] License information could not be automatically verified for the following content:
00:07:08  22:07:08 [INFO] 
00:07:08  22:07:08 [INFO] p2/orbit/p2.eclipse.plugin/org.objectweb.asm.tree/8.0.1.v20200420-1007
```

but it seems this library was approved in https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21853
and its clearlydefined license score shown here
https://clearlydefined.io/definitions/maven/mavencentral/org.ow2.asm/asm-tree/8.0.1
is 60

**Comment by waynebeaton** [comment]
This response is likely going to be "too much information".

The problem is that we don't have any information captured anywhere that maps the ID to the CQ.

ClearlyDefined doesn't know about `p2` artifacts, so there's no help there. It does know about Maven GAVs and it does have data for `org.ow2.asm:asm-tree:8.0.1`, so that's why you get an answer for that.

The backend that supports the Eclipse Dash License Tool doesn't have a mapping from either the bundle name or the Maven GAV to the CQ, so it's no help.

There's a few ways that we can get the backend to support a specific ClearlyDefined ID or Maven GAV:

1. Use either the ClearlyDefined ID or the Maven GAV as the summary in a CQ.
2. I can make a "hint" mapping in the backend data
3. Use the [Automatic IP Team Review Request](https://github.com/eclipse/dash-licenses#automatic-ip-team-review-requests) feature to just request a review.

The referenced CQ actually maps to a bunch of different JARs/bundles, so option 1 isn't going to work. If there was a 1:1 mapping, then we could set the summary of the CQ to `org.ow2.asm:asm-tree:8.0.1` and the tool would then use the information in IPZilla instead of ClearlyDefined. There's a bit of magic that guesses at how GAVs are mapped to bundle names to build a `p2` ID, but I'm pretty sure it wouldn't come up with `org.objectweb.asm.tree` from that GAV (having some kind of consistency in this regard would be helpful). But, again, since the CQ actually maps to multiple GAV/bundles, this won't help in this case anyway.

Since you've alerted me to the issue, I've done option 2. I've configured the tool so that when it encounters IDs for all of the ASM libraries in that CQ that it knows to map them back to that CQ.  It should work now.

As a general rule, though... just use option 3 and the IP Team will take care of it.
