### ISSUE TITLE
project ID only used when request-review is true

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/dash-licenses#233]
I am trying to use the new GitHub actions for Eclipse Orbit (tools.orbit) however I get a different result than I am expecting because the project ID is not being used all the time:

https://github.com/eclipse/dash-licenses/blob/0b14aeb9b97d9741c923beb5ea21ed68a4be8b1d/.github/actions/maven-license-check-action/action.yml#L32-L40

As you can see from the above snippet, project id isn't being passed to maven when request-review is false.

This leads to some differences for Orbit.

With projectId set to tools.cdt, these are the failing items:

```
[INFO] maven/mavencentral/com.sun.media/jai-codec/1.1.3
[INFO] maven/mavencentral/javax.media/jai-core/1.1.3
[INFO] maven/mavencentral/org.apache.httpcomponents/httpclient-win/4.5.14
[INFO] maven/mavencentral/org.apache.sis.core/sis-feature/1.0
[INFO] maven/mavencentral/org.apache.sis.storage/sis-netcdf/1.0
```

without I see these failing

```
[INFO] maven:mavencentral/com.google.code.findbugs/jsr305/1.3.7
[INFO] maven/mavencentral/com.google.code.findbugs/jsr305/1.3.9
[INFO] maven/mavencentral/com.sun.media/jai-codec/1.1.3
[INFO] maven/mavencentral/de.erichseifert.vectorgraphics2d/VectorGraphics2D/0.13
[INFO] maven/mavencentral/edu.ucar/cdm/4.5.5
[INFO] maven/mavencentral/javax.media/jai-core/1.1.3
[INFO] maven/mavencentral/org.apache.httpcomponents/httpclient-win/4.5.14
[INFO] maven/mavencentral/org.apache.sis.core/sis-feature/1.0
[INFO] maven/mavencentral/org.apache.sis.storage/sis-netcdf/1.0
[INFO] maven/mavencentral/org.jacorb/jacorb-omgapi/3.9
[INFO] maven/mavencentral/org.jboss.spec.javax.rmi/jboss-rmi-api_1.0_spec/1.0.6.Final
```

**Comment by waynebeaton** [comment]
Under the old IP Policy we had a notion of "workswith" that granted project-specific approval for some libraries. Some of the entries in the database leverage this notion and corresponding functionality for Eclipse Orbit. Including the project id with the Eclipse Dash License Tool taps into these project-specific approvals.

So... there's two things we can do here.

1. I'll get the IP Team to have a look at the affected records to see if we can just update them to be "approved" under the updated IP Policy; and
2. Update the action to pass the ID (when it is specified).

We need to update the action with care since this is currently being used and just adding the parameter to the `mvn` call will almost certainly break somebody.

I am not familiar with writing or testing GitHub actions, so I'll need some help if we're going to do that (it looks like it's just bash script, so probably easy enough...)

What do you think, @HannesWell ?

**Comment by HannesWell** [comment]
> We need to update the action with care since this is currently being used and just adding the parameter to the `mvn` call will almost certainly break somebody.
> 
> I am not familiar with writing or testing GitHub actions, so I'll need some help if we're going to do that (it looks like it's just bash script, so probably easy enough...)
> 
> What do you think, @HannesWell ?

Sounds good. Just created a draft in #235.
